name: dev
root: ~/

windows:
  - ETC:
      root: ~/Development/local_setup
      panes:
        - clear
  - auth:
      root: ~/Development/local_setup/auth
      panes:
        - cd . && python manage.py runserver
        - nvim README.md
  - onboarding:
      root: ~/Development/local_setup/onboarding
      panes:
        - cd . && python manage.py runserver
        - nvim README.md
  - salesservice:
      root: ~/Development/local_setup/salesservice
      panes:
        - cd server_app && python app.py
        - nvim README.md
  - onboarding_ui:
      root: ~/Development/local_setup/onboarding_ui
      panes:
        - cd . && python manage.py runserver
        - nvim README.md
  - dash-onboard:
      root: ~/Development/local_setup/dashboards/onboarding
      panes:
        - npm run dev
        - nvim README.md
  - dash-white:
      root: ~/Development/local_setup/dashboards/whitelabels
      panes:
        - npm run start
        - nvim README.md
